export const ABM_ACCOUNT_STATUSES: string[] = [
  "Current Customer",
  "Duplicate Account",
  "Inbound Working",
  "Incomplete Data",
  "Incorrect Segment",
  "Incorrect Vertical",
  "Interested (12 months)",
  "Interested (24+ months)",
  "Interested (24 months)",
  "Interested (3-6 months)",
  "Interested (7-12 months)",
  "Interested (Up to 3 months)",
  "No budget",
  "No Interest",
  "Not able to reach",
  "Not looking to upgrade",
  "No Viable Contacts Found",
  "Nurture",
  "Out of Business",
  "Qualified",
  "Recently purchased from competitors",
  "Working",
  "Wrong Fit",
];
